site_name: IREE
logo_link_name: OpenXLA Project
repo_url: https://github.com/iree-org/iree
repo_name: openxla/iree
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/images/openxla-logo-lockup-white.svg
  logo_alt: OpenXLA
  favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: Noto
    code: Noto Sans Mono
  palette:
    # Light mode (scheme overrides in openxla.css)
    - scheme: default
      toggle:
        icon: material/brightness-6
        name: Switch to dark mode
    # Dark mode (scheme overrides in openxla.css)
    - scheme: slate
      toggle:
        icon: material/brightness-6
        name: Switch to light mode
  features:
    - content.code.copy    # Button to copy code snippets
    - content.action.edit  # Button to edit doc source
    - navigation.tabs      # Header tabs for nav items
    - navigation.sections  # Show nav sub-sections (not under zippies)
    - navigation.top       # "Back to top" button
    - navigation.instant   # Ajax-style dynamic loading
    - navigation.tracking  # Update URL in address bar with the active anchor
    - toc.follow           # Scroll the TOC panel to follow the reader
  custom_dir: overrides

extra:
  homepage: https://scottamain.github.io/community
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iree-org/iree
      name: IREE on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/26P4xW4
      name: IREE Discord Server
    - icon: fontawesome/solid/users
      link: https://groups.google.com/forum/#!forum/iree-discuss
      name: IREE Discuss Google Group
  generator: false # TODO(scotttodd): join mkdocs-material insiders for this

extra_css:
  - assets/stylesheets/openxla.css

copyright: Copyright &copy; 2023 The OpenXLA Authors

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:                    # Settings for table of contents
      permalink: 'link'     # Use Material font's "link" icon; see openxla.css
      toc_depth: 3          # Max heading level to include in TOC

# Navigation with explicit ordering and nesting.
# https://www.mkdocs.org/user-guide/configuration/#nav
# Note: may include external links and titles are optional for internal links
nav:
  - Home: "index.md"
  - Get Started:
      - Overview: "getting-started/index.md"
      - TensorFlow: "getting-started/tensorflow.md"
      - TensorFlow Lite: "getting-started/tflite.md"
      - JAX: "getting-started/jax.md"
      - PyTorch: "getting-started/pytorch.md"
      - Deployment configurations:
          - Overview: "deployment-configurations/index.md"
          - CPU: "deployment-configurations/cpu.md"
          - CPU - Bare-Metal: "deployment-configurations/bare-metal.md"
          - GPU - Vulkan: "deployment-configurations/gpu-vulkan.md"
          - GPU - CUDA/ROCm: "deployment-configurations/gpu-cuda-rocm.md"
      - Tools:
          - Optimization Options: "reference/optimization-options.md"
  - API Bindings:
      - Overview: "bindings/index.md"
      - C API: "bindings/c-api.md"
      - Python: "bindings/python.md"
      - TensorFlow Lite: "bindings/tensorflow-lite.md"
  - Developer guides:
      - Build from source:
          - "building-from-source/index.md"
          - "building-from-source/getting-started.md"
          - "building-from-source/python-bindings-and-importers.md"
          - "building-from-source/android.md"
          - "building-from-source/ios.md"
          - "building-from-source/riscv.md"
      - Build an extension:
          - "extensions/index.md"
  - Blog:
      - "blog/index.md"
      - CUDA backend: "blog/2021-10-15-cuda-backend.md"
      - Work in progress on Matrix Multiplication on CPU: "blog/2021-10-13-mmt4d.md"
      - TFLite Support via TOSA: "blog/2021-07-19-tflite-tosa.md"
  - "Community":
      - "community/index.md"
